### ISSUE TITLE
Whats the font in image?

### ISSUE THREAD

**Issue by zhondori** [pabueco/cotion-vscode-theme#1]
Hello , can you tell what is font that you used in image on marketplace?

**Comment by pabueco** [comment]
Hi, the font is [Iosevka](https://typeof.net/Iosevka/). Specifically the "Curly" and "Extended" variant. You can get it from [GitHub](https://github.com/be5invis/Iosevka).
You need to download "Iosevka Curly" and then set the font family in your editor to "Iosevka Curly Extended".

**Comment by zhondori** [comment]
Thanks bro!
